# Generated by Django 3.0 on 2020-02-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approvedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
