# Generated by Django 3.0 on 2020-02-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_app', '0002_auto_20200203_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
