# Generated by Django 3.0 on 2020-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_app', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, default='off', max_length=10, null=True),
        ),
    ]
