# Generated by Django 3.0 on 2020-02-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_app', '0006_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
